### ISSUE TITLE
Type aliases for functions are broken

### ISSUE THREAD

**Issue by evansimmons-ck** [babel/acorn-babel#29]
```
var a = require('acorn')
a.parse('type F<U, V> = ((x: U) => V);')
{ type: null, start: 0, end: null }
SyntaxError: Unexpected token (1:23)
    at raise (/Users/evan.simmons/repos/acorn-babel/acorn.js:343:15)
    at unexpected (/Users/evan.simmons/repos/acorn-babel/acorn.js:2297:5)
    at expect (/Users/evan.simmons/repos/acorn-babel/acorn.js:2285:18)
    at parsePrimaryType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4714:9)
    at parsePostfixType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4744:35)
    at parsePrefixType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4759:12)
    at parseIntersectionType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4764:16)
    at parseUnionType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4774:16)
    at parseType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4785:16)
    at parsePrimaryType (/Users/evan.simmons/repos/acorn-babel/acorn.js:4688:20)
```

**Comment by sebmck** [comment]
Hm, seems to work in the [REPL](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=true&spec=false&code=type%20F%3CU%2C%20V%3E%20%3D%20((x%3A%20U)%20%3D%3E%20V)%3B%0A%0Afoo%3B).
